CREATE TABLE RASPISANIE
(
    id     INT AUTO_INCREMENT PRIMARY KEY,
    timeslot VARCHAR(10) NOT NULL,
    group1 INT(10) NOT NULL,
    group2 INT(10) NOT NULL
);

INSERT INTO RASPISANIE VALUES (1, '11', 1, 2 );

CREATE TABLE STUDENTGROUP
(
    id INT AUTO_INCREMENT PRIMARY KEY,
    number VARCHAR(10) NOT NULL
);

INSERT INTO STUDENTGROUP VALUES (1, 'группа 1');
INSERT INTO STUDENTGROUP VALUES (2, 'группа 2');
INSERT INTO STUDENTGROUP VALUES (3, 'группа 3');
INSERT INTO STUDENTGROUP VALUES (4, 'группа 4');
INSERT INTO STUDENTGROUP VALUES (5, 'группа 5');
INSERT INTO STUDENTGROUP VALUES (6, 'группа 6');
INSERT INTO STUDENTGROUP VALUES (7, 'группа 7');

CREATE TABLE AUDITORY
(
    id INT AUTO_INCREMENT PRIMARY KEY,
    number VARCHAR(10) NOT NULL
);

INSERT INTO AUDITORY VALUES (1, '1');
INSERT INTO AUDITORY VALUES (2, '2');
INSERT INTO AUDITORY VALUES (3, '3');

CREATE TABLE TEACHERS
(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

INSERT INTO TEACHERS VALUES (1, 'Иванов И.И.');
INSERT INTO TEACHERS VALUES (2, 'Петров П.П.');
INSERT INTO TEACHERS VALUES (3, 'Сидоров С.С.');
INSERT INTO TEACHERS VALUES (4, 'Григорьев Г.Г.');

CREATE TABLE THURSDAY
(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

-- INSERT INTO THURSDAY VALUES (1, 'Свободный четверг');