CREATE TABLE RASPISANIE
(
    id     INT AUTO_INCREMENT PRIMARY KEY,
    timeslot VARCHAR(10) NOT NULL,
    group1 INT(10) NOT NULL,
    group2 INT(10) NOT NULL
);

INSERT INTO RASPISANIE VALUES (1, '11', 1, 2 );